In [1]:
import jax.numpy as jnp

M = jnp.arange(16).reshape(4, 4)
x = jnp.arange(4)
y = jnp.array([5, 4, 3, 2])

In [15]:
M

Array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]], dtype=int32)

In [14]:
M.sum(axis=0)

Array([24, 28, 32, 36], dtype=int32)

In [4]:
x

Array([0, 1, 2, 3], dtype=int32)

In [27]:
jnp.einsum('ij,j->j', M, x)

Array([  0,  28,  64, 108], dtype=int32)

In [ ]:
jnp.dot(x)

Array([56, 62, 68, 74], dtype=int32)

In [ ]:
import sys
import os
sys.path.append(os.path.abspath('..')) 

from notebooks.utils.config import Config

cfg = Config()

/Users/m-seince/miniconda3/envs/abbfn2/lib/python3.11/site-packages/hydra/_internal/config_loader_impl.py:216: UserWarning: provider=hydra.searchpath in main, path=./configs is not available.
  warnings.warn(


In [3]:
cfg

{'run': {'output_network': {'backbone': {'_target_': 'abbfn2.bfn.output_network.backbone.backbone.TransformerBackbone', 'cfg': {'_target_': 'abbfn2.bfn.output_network.backbone.backbone.BackboneConfig', 'embed_dim': 1280, 'key_size': 64, 'attention_heads': 20, 'ffn_embed_dim': 5120, 'num_layers': 33}}}, 'data_mode': {'h_fwr1_seq': {'handler': {'tokenizer': {'_target_': 'abbfn2.data.data_mode_handler.sequence.utils.BFNTokenizer', 'standard_tokens': ['A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V', 'X', 'B', 'Z', 'J', 'U', 'O'], 'fixed_length': 43, 'crop_method': 'random', 'unk_token': '<unk>', 'pad_token': '<pad>', 'mask_token': '<mask>', 'class_token': '<cls>"', 'eos_token': '<eos>', 'bos_token': '<bos>', 'prepend_bos_token': True, 'prepend_cls_token': False, 'append_eos_token': True, 'extra_special_tokens': None, 'tokens_to_ids': None}, '_target_': 'abbfn2.data.data_mode_handler.sequence.sequence.SequenceDataModeHandler', 'sequence_var

In [4]:
from dotenv import load_dotenv
import os
load_dotenv()

print(os.getenv("HUGGINGFACE_TOKEN"))

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


In [2]:
pip install python-dotenv

Note: you may need to restart the kernel to use updated packages.


In [1]:
from abbfn2.data.data_mode_handler.utils import load_from_hdf5

def hdf5_to_dict(filepath):
    """Convert an HDF5 file to a dictionary.
    
    Args:
        filepath (str): Path to the HDF5 file
        
    Returns:
        dict: Dictionary containing the HDF5 data
    """
    return load_from_hdf5(filepath)


a = hdf5_to_dict('/Users/m-seince/Documents/Research/AbBFN2/AbBFN2/outputs/2025-04-07/15-50-42/validation/inpaint/unconditional_gen/properties.hdf5')

In [2]:
a

{'h_cdr1_len': array([8]),
 'h_cdr2_len': array([8]),
 'h_cdr3_len': array([14]),
 'h_d_call': 'IGHD6-6',
 'h_d_call_family': 'IGHD6',
 'h_d_identity': array([[87.12813]], dtype=float32),
 'h_j_call': 'IGHJ6',
 'h_j_call_family': 'IGHJ6',
 'h_j_identity': array([[87.349686]], dtype=float32),
 'h_v_call': 'IGHV3-23',
 'h_v_call_family': 'IGHV3',
 'h_v_identity': array([[82.48627]], dtype=float32),
 'l_cdr1_len': array([6]),
 'l_cdr2_len': array([3]),
 'l_cdr3_len': array([9]),
 'l_j_call': 'IGKJ4',
 'l_j_call_family': 'IGKJ4',
 'l_j_identity': array([[88.28449]], dtype=float32),
 'l_locus': 'K',
 'l_v_call': 'IGKV1-5',
 'l_v_call_family': 'IGKV1',
 'l_v_identity': array([[82.82195]], dtype=float32),
 'pnc': array([[4.906002]], dtype=float32),
 'pnc_flag': 'red',
 'ppc': array([[3.7259445]], dtype=float32),
 'ppc_flag': 'green',
 'psh': array([[187.57986]], dtype=float32),
 'psh_flag': 'amber',
 'sfvcsp': array([[0.97789]], dtype=float32),
 'sfvcsp_flag': 'green',
 'species': 'human'}